name: Build Games
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - pterodactyl/games/**
jobs:
  push:
    name: "game_${{ matrix.game.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - folder: minecraft/bds
            tag: minecraft_bds

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./pterodactyl/games/${{ matrix.game.folder }}
          file: ./pterodactyl/games/${{ matrix.game.folder }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/artuto/egg:games/${{ matrix.game.tag }}
