name: Build Java
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - pterodactyl/java/**
jobs:
  push:
    name: "java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 17_msopenjdk
          - 21_msopenjdk
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./pterodactyl/java
          file: ./pterodactyl/java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/artuto/egg:java_${{ matrix.tag }}
